### ISSUE TITLE
sendBatch() needs return value otherwise lambda will terminate main thread before metrics sent out

### ISSUE THREAD

**Issue by XingzhiWang** [newrelic/newrelic-telemetry-sdk-java#194] opened 2020-06-22 17:48 UTC
Hi, 
I am using TelemetryClient sendBatch() function in my AWS Lambda. However, lambda will exist without completing sending metrics. 
A similar problem is here : https://stackoverflow.com/questions/31633912/how-to-wait-for-async-actions-inside-aws-lambda 
Maybe adding a result for the asynchronous call is a better solution ? 
Thanks!

**Comment by breedx-nr** [comment] 2020-07-15 21:35
@XingzhiWang I am closing this as a duplicate of #166, but if you think it's different please reopen with an explanation.  Thanks!

**Closed by breedx-nr** 2020-07-15 21:35 UTC
